### ISSUE TITLE
dns server to handle subdomain

### ISSUE THREAD

**Issue by furick1** [joyofhex/cookbook-bind#23]
I have been able to use your cookbook to create a bind (named) dns server on centos 6.7 using the default options.  However, i'm having difficulty creating a custom zone.  Can anyone assist with a attribute/default.rb wrapper for this cookbook? What i want is to create a dns server to answer for hosts in subdomain.xyz.com and send any other queries for xyz.com dns requests to the parent dns server. i also want to enable dynamic updates.

I get an error about can't find file when trying to set bind.zones.attribute to subdomain. Do I need to add a file to files/default/.....?

 ================================================================================
23:09:10.144 10.3.30.150     Error executing action `run` on resource 'execute[named-checkconf]'
23:09:10.144 10.3.30.150     ================================================================================
23:09:10.144 10.3.30.150  
23:09:10.144 10.3.30.150     Mixlib::ShellOut::ShellCommandFailed
23:09:10.144 10.3.30.150     ------------------------------------
23:09:10.145 10.3.30.150     Expected process to exit with [0], but received '1'
23:09:10.145 10.3.30.150     ---- Begin output of /usr/sbin/named-checkconf -z /etc/named.conf ----
23:09:10.145 10.3.30.150     STDOUT: zone localhost.localdomain/IN: loaded serial 0
23:09:10.145 10.3.30.150     zone localhost/IN: loaded serial 0
23:09:10.145 10.3.30.150     zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
23:09:10.146 10.3.30.150     zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
23:09:10.146 10.3.30.150     zone 0.in-addr.arpa/IN: loaded serial 0
23:09:10.146 10.3.30.150     zone bind/IN: loading from master file master/db.bind failed: file not found
23:09:10.146 10.3.30.150     zone bind/IN: not loaded due to errors.
23:09:10.146 10.3.30.150     zone subdomain.xyz.com/IN: loading from master file master/db.subdomain.xyz.com failed: file not found
23:09:10.146 10.3.30.150     zone subdomain.xyz.com/IN: not loaded due to errors.
23:09:10.147 10.3.30.150     STDERR: _default/bind/in: file not found
23:09:10.147 10.3.30.150     _default/subdomain.xyz.com/in: file not found
23:09:10.147 10.3.30.150     ---- End output of /usr/sbin/named-checkconf -z /etc/named.conf ----
23:09:10.147 10.3.30.150     Ran /usr/sbin/named-checkconf -z /etc/named.conf returned 1

**Comment by bcg62** [comment]
Im also seeing this

**Comment by joyofhex** [comment]
This is a bit simpler now with the v2 of the cookbook. You can use either the bind_primary_zone resource (if you have a file containing the zone data), or the bind_primary_zone_template resource (if you wish to provide the records to go in the zone separately).
