### ISSUE TITLE
Maintain VERSION with non-repo .gitignore(d) file suitability

### ISSUE THREAD

**Issue by benvaljean** [joyofhex/cookbook-bind#24]
May I ask, what is the motive for maintaining the VERSION file not as part of the repo? If I am to use this cookbook unmodified I would need fork it locally to add the VERSION file if using librarrian / berkshelf. Would it be easier to add it to the repo? Is there a reason why you prefer to let users of the cookbook maintain the version themselves?

Incidentally the rescue syntax in metadata.rb  https://github.com/atomic-penguin/cookbook-bind/blob/master/metadata.rb#L6   does not appear to work with Chef (11.0.11-1.el6) as the version when uploaded is 0.0.0 . Perhaps it is not supported in this version though.

**Comment by joyofhex** [comment]
I don't believe we're doing this anymore. However, note that this cookbook no longer supports chef 11.
