### ISSUE TITLE
chroot support ?

### ISSUE THREAD

**Issue by mengesb** [joyofhex/cookbook-bind#31]
Looks like I'm unable to get this cookbook to support `bind-chroot` on CentOS 7.x. The single-use implementation of the `sysconfdir` and `vardir` elements mean you can't set the right context in the `named.options` file for includes or other related settings.

I've tried
```ruby
bind_service 'default' do
  action [:create]
  package_name 'bind-chroot'
  service_name 'named-chroot'
  sysconfdir '/var/named/chroot/etc/named'
  vardir '/var/named/chroot/var/named'
end

bind_config 'default' do
  ipv6_listen false
  conf_file '/var/named/chroot/etc/named.conf'
  options bind_opts
  options_file '/var/named/chroot/etc/named/named.options'
  query_log node['my_dns']['config']['query']['log']['path']
  query_log_max_size node['my_dns']['config']['query']['log']['max_size']
  query_log_options node['my_dns']['config']['query']['log']['options']
  query_log_versions node['my_dns']['config']['query']['log']['versions']
  statistics_channel node['my_dns']['config']['statistics_channel']
end
```

However that would require a directory structure of:
`/var/named/chroot/etc/named/var/named/chroot/etc/named.conf` for named.conf instead of `/var/named/chroot/etc/named.conf`
`/var/named/chroot/var/named/chroot/etc/named/named.options` for named.options instead of `/var/named/chroot/etc/named/named.options`

It would seem the best course of action is to allow some base-directory setting for chroot enabled environments to allow the difference between `sysconfdir`/`vardir` with and without chroot context

**Comment by mengesb** [comment]
Looks like you also don't allow for a different cookbook or template files for the main `named.conf` or `named.options` files either... so effectively the `chroot` option has to be built-in as a boolean with assumptions made, or those configs allowed to configure from different cookbooks/templates

**Comment by joyofhex** [comment]
Thanks for the contribution on this. I'm sorry I'd not seen you raise the initial issue. Still some tweaking the notifications on github it seems.

**Comment by pavel-shvagirev** [comment]
You may like to add the following apparmor config in order to make chrooting work on Ubuntu 18.04:
`
$ cat ../templates/default/apparmor_usr.sbin.named.erb
# This file was generated by Chef
# Do NOT modify this file by hand!

<%= node['bind9']['chroot_dir'] %>/** rwm,
$
`
recipe:
`
bind_service 'default' do
    chroot true
    chroot_dir node['bind9']['chroot_dir']
...
`
`
service 'bind9' do
end

service 'apparmor' do
end

template '/etc/apparmor.d/local/usr.sbin.named' do
    source 'apparmor_usr.sbin.named.erb'
    notifies :reload, 'service[apparmor]', :immediate
    notifies :restart, 'service[bind9]', :delayed
end
`
