### ISSUE TITLE
RFC1035 - maximum hostname record length = width of owner

### ISSUE THREAD

**Issue by mengesb** [joyofhex/cookbook-bind#34]
RFC1035 spec:
* maximum record length = 255
* maximum dotted quad length 63 characters (+ dot = 64 ; delimiter)

Per RFC, the maximum hostname length then can be 63, so update to the `owner` field should be a width of 63 + padding; call it 65 for safety.

Since we don't handle zone types differently (reverse vs forward), this padding looks funny on a reverse zone but eh; still nice to keep them all consistent anwyay...

#33 submitted to address this issue

**Comment by joyofhex** [comment]
#33 merged!
