### ISSUE TITLE
push version 2.1.1 to supermarket

### ISSUE THREAD

**Issue by bugoff** [joyofhex/cookbook-bind#40]
Hi,

I was just wrapping your cookbook, and i need to use the zone_name in one of my cookbooks. Could you push version 2.1.1 to chef supermarket?

Thx!

**Comment by joyofhex** [comment]
Thanks for your patience. The zone_name property was added during the work for implementing views. I'm just waiting for some feedback on #42 / #38 from the requestor and once that's merged I'll push a 2.2 to supermarket. Hopefully will be done in the next couple of days.

**Comment by joyofhex** [comment]
I've pushed v2.2.0 to the supermarket which should have the changes you wanted.
