### ISSUE TITLE
wishlist: add support for dynamic primary zone

### ISSUE THREAD

**Issue by huckley** [joyofhex/cookbook-bind#41]
Hello,

I wish the support for dynamic primary zones, which means zones that can be updated via nsupdate.
The first draft is create only a zonefile if that zonefile not exists.

**Comment by joyofhex** [comment]
I propose to support this by adding a :create_if_missing action to the primary_zone custom resource to mirror what's done by the file resource. This wouldn't persist the data any place. If you were to rebuild the host there wouldn't be any way of starting with that data intact. Does that seem reasonable as a start?

**Comment by joyofhex** [comment]
Released in v2.2.0.
