### ISSUE TITLE
Add a note about chefignore by default ignoring .com files to your README

### ISSUE THREAD

**Issue by indygwyn** [joyofhex/cookbook-bind#51]

**Comment by joyofhex** [comment]
Interesting. I think that file comes from a default created by one of the various chef tools. As I can't imagine any case where there a .COM file would come into existence perhaps just removing that entry from chefignore is best?

**Comment by indygwyn** [comment]
Yup, if you do a `chef generate cookbook blah` you'll get a default chefignore, with .exe .dll .com etc, but it took me quite awhile to figure out why it would never see my example.com file, a quick note in the readme might help others not miss this.
