### ISSUE TITLE
chroot in Ubuntu 18.04

### ISSUE THREAD

**Issue by pavel-shvagirev** [joyofhex/cookbook-bind#52]
@joyofhex you may like to add the following apparmor config in order to make chrooting work on Ubuntu 18.04:

> $ cat ../templates/default/apparmor_usr.sbin.named.erb
> <%= node['bind9']['chroot_dir'] %>/** rwm,
> $

recipe:

> bind_service 'default' do
>     chroot true
>     chroot_dir node['bind9']['chroot_dir']

and:

> service 'bind9' do
> end
> 
> service 'apparmor' do
> end
> 
> template '/etc/apparmor.d/local/usr.sbin.named' do
>     source 'apparmor_usr.sbin.named.erb'
>     notifies :reload, 'service[apparmor]', :immediate
>     notifies :restart, 'service[bind9]', :delayed
> end

_Originally posted by @pavel-shvagirev in https://github.com/joyofhex/cookbook-bind/issues/31#issuecomment-459983809_

**Comment by joyofhex** [comment]
I've added some experimental apparmor config in the referenced PR, which I'll shortly merge to master. Would you be willing to give it a try out to see if it works for your use case? 

Thanks!

**Comment by joyofhex** [comment]
Released in v2.3.0 of the cookbook.
