### ISSUE TITLE
Wishlist: add support for stub zone

### ISSUE THREAD

**Issue by huckley** [joyofhex/cookbook-bind#53]
Hello,

I wish the support for stub zones.
maybe it is also a good Idea to support all the other zone types of bind:
http://www.zytrax.com/books/dns/ch7/zone.html#type

**Comment by joyofhex** [comment]
I've been adding additional zone types when someone asks for them. I'll start work on putting in stub zones to the cookbook.

**Comment by joyofhex** [comment]
I've added a branch that adds in a `bind_stub_zone` resource. Can you try it out and see if it does what you want it to?

Thanks

**Comment by joyofhex** [comment]
Released in v2.3.0 of the cookbook.
